# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FacebookUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 498)
        self.sideBar = QtWidgets.QFrame(Form)
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 97, 501))
        self.sideBar.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addGrpBtn = QtWidgets.QPushButton(self.sideBar)
        self.addGrpBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("multiple-users-silhouette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addGrpBtn.setIcon(icon)
        self.addGrpBtn.setIconSize(QtCore.QSize(50, 50))
        self.addGrpBtn.setObjectName("addGrpBtn")
        self.verticalLayout.addWidget(self.addGrpBtn)
        self.addImageBtn = QtWidgets.QPushButton(self.sideBar)
        self.addImageBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("image (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImageBtn.setIcon(icon1)
        self.addImageBtn.setIconSize(QtCore.QSize(60, 60))
        self.addImageBtn.setObjectName("addImageBtn")
        self.verticalLayout.addWidget(self.addImageBtn)
        self.clearGrpsBtn = QtWidgets.QPushButton(self.sideBar)
        self.clearGrpsBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("remove grp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearGrpsBtn.setIcon(icon2)
        self.clearGrpsBtn.setIconSize(QtCore.QSize(60, 60))
        self.clearGrpsBtn.setObjectName("clearGrpsBtn")
        self.verticalLayout.addWidget(self.clearGrpsBtn)
        self.clearImages = QtWidgets.QPushButton(self.sideBar)
        self.clearImages.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("remove images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearImages.setIcon(icon3)
        self.clearImages.setIconSize(QtCore.QSize(60, 60))
        self.clearImages.setObjectName("clearImages")
        self.verticalLayout.addWidget(self.clearImages)
        self.exitBtn = QtWidgets.QPushButton(self.sideBar)
        self.exitBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("power-on.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon4)
        self.exitBtn.setIconSize(QtCore.QSize(50, 50))
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(100, 0, 801, 501))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(resource_path("background.jpg")))
        self.background.setScaledContents(False)
        self.background.setObjectName("background")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(130, 40, 101, 101))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(resource_path("facebook.png")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 33, 641, 101))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.timer = QtWidgets.QLineEdit(Form)
        self.timer.setGeometry(QtCore.QRect(350, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.timer.setFont(font)
        self.timer.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.timer.setObjectName("timer")
        self.tiimerText = QtWidgets.QLabel(Form)
        self.tiimerText.setGeometry(QtCore.QRect(110, 180, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.tiimerText.setFont(font)
        self.tiimerText.setObjectName("tiimerText")
        self.statusText = QtWidgets.QLabel(Form)
        self.statusText.setGeometry(QtCore.QRect(160, 260, 231, 221))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.statusText.setFont(font)
        self.statusText.setStyleSheet("color: rgb(255, 0, 0);\n"
"text-align: center;")
        self.statusText.setAlignment(QtCore.Qt.AlignCenter)
        self.statusText.setWordWrap(True)
        self.statusText.setObjectName("statusText")
        self.keyword = QtWidgets.QLineEdit(Form)
        self.keyword.setGeometry(QtCore.QRect(470, 160, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.keyword.setFont(font)
        self.keyword.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.keyword.setClearButtonEnabled(True)
        self.keyword.setObjectName("keyword")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(630, 450, 121, 41))
        self.start.setStyleSheet("background-color:#16C2DC;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.start.setObjectName("start")
        self.maxGrpToFetch = QtWidgets.QLineEdit(Form)
        self.maxGrpToFetch.setGeometry(QtCore.QRect(760, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.maxGrpToFetch.setFont(font)
        self.maxGrpToFetch.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.maxGrpToFetch.setObjectName("maxGrpToFetch")
        self.postText = QtWidgets.QPlainTextEdit(Form)
        self.postText.setGeometry(QtCore.QRect(470, 210, 421, 231))
        self.postText.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"")
        self.postText.setObjectName("postText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "acebook Group Poster"))
        self.timer.setPlaceholderText(_translate("Form", "timer"))
        self.tiimerText.setText(_translate("Form", "Set Timer (seconds):"))
        self.statusText.setText(_translate("Form", "The status of the program will be displayed here"))
        self.keyword.setPlaceholderText(_translate("Form", "If u want to post by keyword"))
        self.start.setText(_translate("Form", "Start"))
        self.maxGrpToFetch.setPlaceholderText(_translate("Form", "max no. Grps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
