# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InstagramUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 500)
        Form.setMinimumSize(QtCore.QSize(900, 500))
        Form.setMaximumSize(QtCore.QSize(900, 500))
        self.sideBar = QtWidgets.QFrame(Form)
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 191, 501))
        self.sideBar.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.logo = QtWidgets.QLabel(self.sideBar)
        self.logo.setGeometry(QtCore.QRect(20, 10, 141, 141))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(resource_path("instagram.png")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.followersRadioBtn = QtWidgets.QRadioButton(self.sideBar)
        self.followersRadioBtn.setGeometry(QtCore.QRect(10, 150, 178, 65))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.followersRadioBtn.setFont(font)
        self.followersRadioBtn.setStyleSheet("padding: 10px;\n"
"color: #fff;")
        self.followersRadioBtn.setObjectName("followersRadioBtn")
        self.followingRadioBtn = QtWidgets.QRadioButton(self.sideBar)
        self.followingRadioBtn.setGeometry(QtCore.QRect(10, 230, 178, 65))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.followingRadioBtn.setFont(font)
        self.followingRadioBtn.setStyleSheet("padding: 10px;\n"
"color: #fff;")
        self.followingRadioBtn.setObjectName("followingRadioBtn")
        self.exitBtn = QtWidgets.QPushButton(self.sideBar)
        self.exitBtn.setGeometry(QtCore.QRect(50, 360, 71, 71))
        self.exitBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("power-on.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon)
        self.exitBtn.setIconSize(QtCore.QSize(50, 50))
        self.exitBtn.setObjectName("exitBtn")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(190, 0, 711, 501))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(resource_path("background.jpg")))
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 34, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 160, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 260, 201, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(200, 310, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(200, 360, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.targetAudienceUserName = QtWidgets.QLineEdit(Form)
        self.targetAudienceUserName.setGeometry(QtCore.QRect(560, 150, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.targetAudienceUserName.setFont(font)
        self.targetAudienceUserName.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.targetAudienceUserName.setObjectName("targetAudienceUserName")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(230, 210, 331, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.timer = QtWidgets.QLineEdit(Form)
        self.timer.setGeometry(QtCore.QRect(560, 200, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.timer.setFont(font)
        self.timer.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.timer.setObjectName("timer")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(340, 300, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(340, 350, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
"border-radius: 5px;")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(380, 420, 121, 41))
        self.start.setStyleSheet("background-color:#16C2DC;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.start.setObjectName("start")
        self.statusText = QtWidgets.QLabel(Form)
        self.statusText.setGeometry(QtCore.QRect(640, 260, 241, 231))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.statusText.setFont(font)
        self.statusText.setStyleSheet("color: rgb(255, 0, 0);\n"
"text-align: center;")
        self.statusText.setScaledContents(False)
        self.statusText.setAlignment(QtCore.Qt.AlignCenter)
        self.statusText.setWordWrap(True)
        self.statusText.setObjectName("statusText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.followersRadioBtn.setText(_translate("Form", "Followers"))
        self.followingRadioBtn.setText(_translate("Form", "Following"))
        self.label.setText(_translate("Form", "Email Fetcher"))
        self.label_2.setText(_translate("Form", "Target Audience Username:"))
        self.label_3.setText(_translate("Form", "USER INFO"))
        self.label_4.setText(_translate("Form", "Username:"))
        self.label_5.setText(_translate("Form", "Password:"))
        self.label_6.setText(_translate("Form", "Set Break Timer (Seconds):"))
        self.start.setText(_translate("Form", "Start"))
        self.statusText.setText(_translate("Form", "Status Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
